# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e9951c0cd3887db34c0abecebc49211a"
name = "shortenly"
handle = "shortenly-1"
application_url = "https://measuring-capabilities-manufacture-bedroom.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://measuring-capabilities-manufacture-bedroom.trycloudflare.com/auth/callback",
  "https://measuring-capabilities-manufacture-bedroom.trycloudflare.com/auth/shopify/callback",
  "https://measuring-capabilities-manufacture-bedroom.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
